# Generated by Django 5.1 on 2024-08-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Familia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=20, null=True)),
                ("lider_familia", models.CharField(max_length=100)),
                ("dt_nasc_lider", models.DateField()),
                ("cidade_estado_nasc_lider", models.CharField(max_length=100)),
                ("profissao_lider", models.CharField(max_length=100)),
                ("escolaridade_lider", models.CharField(max_length=100)),
                ("cpf_lider", models.CharField(max_length=14)),
                ("rg_lider", models.CharField(max_length=20)),
                ("conjuge", models.CharField(blank=True, max_length=100, null=True)),
                ("dt_nasc_conjuge", models.DateField(blank=True, null=True)),
                (
                    "cidade_estado_nasc_conjuge",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "profissao_conjuge",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "escolaridade_conjuge",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cpf_conjuge", models.CharField(blank=True, max_length=14, null=True)),
                ("rg_conjuge", models.CharField(blank=True, max_length=20, null=True)),
                ("estado_civil", models.CharField(max_length=15)),
                ("religiao", models.CharField(max_length=100)),
                ("bolsa_familia", models.BooleanField(default=False)),
                ("outro_beneficio", models.BooleanField(default=False)),
                (
                    "renda_familiar",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tempo_bairro", models.CharField(max_length=100)),
                ("tempo_cidade", models.CharField(max_length=100)),
                ("residencia", models.CharField(max_length=20)),
                ("qt_dependentes", models.IntegerField(blank=True, null=True)),
                ("carteira_vacinacao", models.BooleanField(default=True)),
                (
                    "doenca_cronica",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("qt_outros_moradores", models.IntegerField(blank=True, null=True)),
                ("contato", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=200)),
                ("tel_fixo", models.CharField(blank=True, max_length=15, null=True)),
                ("celular", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("data_visita", models.DateField()),
                ("responsavel_visita", models.CharField(max_length=100)),
            ],
        ),
    ]
