# Generated by Django 5.1 on 2024-08-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_familia_filho_10_escola_familia_filho_10_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="familia",
            name="observacoes",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
