# Generated by Django 5.1 on 2024-08-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0005_alter_familia_estado_civil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familia",
            name="renda_familiar",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
