# Generated by Django 5.1 on 2024-08-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0006_alter_familia_renda_familiar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familia",
            name="qt_dependentes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="familia",
            name="qt_outros_moradores",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="familia",
            name="qtd_filhos",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
