# Generated by Django 5.1 on 2024-08-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0007_alter_familia_qt_dependentes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familia",
            name="responsavel_visita",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
