# Generated by Django 5.1 on 2024-08-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0008_alter_familia_responsavel_visita"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familia",
            name="estado_civil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("solteiro", "Solteiro"),
                    ("casado", "Casado"),
                    ("religioso", "Religioso"),
                    ("viuvo", "Viúvo"),
                    ("uniaoEstavel", "União Estável"),
                ],
                default="solteiro",
                max_length=15,
                null=True,
            ),
        ),
    ]
