# Generated by Django 5.1 on 2024-08-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0009_alter_familia_estado_civil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familia",
            name="celular",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="familia",
            name="cidade_estado_nasc_lider",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="familia",
            name="contato",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="familia",
            name="cpf_lider",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name="familia",
            name="data_visita",
            field=models.DateField(blank=True, default="2024/08/19", null=True),
        ),
        migrations.AlterField(
            model_name="familia",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="familia",
            name="endereco",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="familia",
            name="escolaridade_lider",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="familia",
            name="observacoes",
            field=models.CharField(blank=True, default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="familia",
            name="profissao_lider",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="familia",
            name="religiao",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="familia",
            name="residencia",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="familia",
            name="rg_lider",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="familia",
            name="tempo_bairro",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="familia",
            name="tempo_cidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="filho",
            name="dt_nasc",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="filho",
            name="nome",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
