# Generated by Django 5.1 on 2024-08-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0010_alter_familia_celular_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familia",
            name="codigo",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
