# Generated by Django 5.1 on 2024-08-25 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0011_alter_familia_codigo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="familia",
            old_name="qtd_filhos",
            new_name="qt_filhos",
        ),
        migrations.RenameField(
            model_name="filho",
            old_name="dt_nasc",
            new_name="dt_nasc_filho",
        ),
        migrations.AlterField(
            model_name="familia",
            name="data_visita",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
