# Generated by Django 6.0.3 on 2026-03-31 21:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_rename_qtd_filhos_familia_qt_filhos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('documento', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('financeira', 'Financeira'), ('alimentos', 'Alimentos'), ('vestuario', 'Vestuário'), ('higiene', 'Higiene'), ('material_escolar', 'Material Escolar'), ('outros', 'Outros')], default='financeira', max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('unidade', models.CharField(blank=True, default='', max_length=30)),
                ('data_doacao', models.DateField(default=datetime.date.today)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes_registradas', to=settings.AUTH_USER_MODEL)),
                ('doador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes', to='cadastros.doador')),
            ],
            options={
                'ordering': ['-data_doacao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Repasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('financeira', 'Financeira'), ('alimentos', 'Alimentos'), ('vestuario', 'Vestuário'), ('higiene', 'Higiene'), ('material_escolar', 'Material Escolar'), ('outros', 'Outros')], default='financeira', max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('unidade', models.CharField(blank=True, default='', max_length=30)),
                ('data_repasse', models.DateField(default=datetime.date.today)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='entregue', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('doacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repasses', to='cadastros.doacao')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repasses', to='cadastros.familia')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repasses_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_repasse', '-id'],
            },
        ),
    ]
