# Generated by Django 6.0.3 on 2026-04-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_doador_doacao_repasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(choices=[('nao_aplicavel', 'Não se aplica'), ('cesta_basica', 'Cesta básica'), ('feijao', 'Feijão'), ('arroz', 'Arroz'), ('oleo', 'Óleo'), ('brinquedos', 'Brinquedos'), ('fraldas', 'Fraldas'), ('leite', 'Leite'), ('roupas', 'Roupas'), ('higiene', 'Itens de higiene'), ('material_escolar', 'Material escolar'), ('outros', 'Outros')], max_length=30, unique=True)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('unidade', models.CharField(blank=True, default='un', max_length=30)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['produto'],
            },
        ),
        migrations.AddField(
            model_name='doacao',
            name='produto',
            field=models.CharField(choices=[('nao_aplicavel', 'Não se aplica'), ('cesta_basica', 'Cesta básica'), ('feijao', 'Feijão'), ('arroz', 'Arroz'), ('oleo', 'Óleo'), ('brinquedos', 'Brinquedos'), ('fraldas', 'Fraldas'), ('leite', 'Leite'), ('roupas', 'Roupas'), ('higiene', 'Itens de higiene'), ('material_escolar', 'Material escolar'), ('outros', 'Outros')], default='nao_aplicavel', max_length=30),
        ),
        migrations.AddField(
            model_name='repasse',
            name='produto',
            field=models.CharField(choices=[('nao_aplicavel', 'Não se aplica'), ('cesta_basica', 'Cesta básica'), ('feijao', 'Feijão'), ('arroz', 'Arroz'), ('oleo', 'Óleo'), ('brinquedos', 'Brinquedos'), ('fraldas', 'Fraldas'), ('leite', 'Leite'), ('roupas', 'Roupas'), ('higiene', 'Itens de higiene'), ('material_escolar', 'Material escolar'), ('outros', 'Outros')], default='nao_aplicavel', max_length=30),
        ),
    ]
