# Generated by Django 6.0.3 on 2026-04-03 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_estoqueitem_doacao_produto_repasse_produto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AuditoriaEstoqueValidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('bloqueio_doacao_vencido', 'Bloqueio de doação vencida'), ('reauth_falha', 'Reautenticação falhou'), ('reauth_sucesso', 'Reautenticação com sucesso'), ('repasse_vencido_confirmado', 'Repasse vencido confirmado'), ('alerta_email_enviado', 'Alerta de validade por e-mail enviado'), ('alerta_email_erro', 'Erro ao enviar alerta de validade por e-mail')], max_length=40)),
                ('produto', models.CharField(blank=True, choices=[('nao_aplicavel', 'Não se aplica'), ('cesta_basica', 'Cesta básica'), ('feijao', 'Feijão'), ('arroz', 'Arroz'), ('oleo', 'Óleo'), ('brinquedos', 'Brinquedos'), ('fraldas', 'Fraldas'), ('leite', 'Leite'), ('roupas', 'Roupas'), ('higiene', 'Itens de higiene'), ('material_escolar', 'Material escolar'), ('outros', 'Outros')], default='', max_length=30)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('mensagem', models.CharField(max_length=255)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_validade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(choices=[('nao_aplicavel', 'Não se aplica'), ('cesta_basica', 'Cesta básica'), ('feijao', 'Feijão'), ('arroz', 'Arroz'), ('oleo', 'Óleo'), ('brinquedos', 'Brinquedos'), ('fraldas', 'Fraldas'), ('leite', 'Leite'), ('roupas', 'Roupas'), ('higiene', 'Itens de higiene'), ('material_escolar', 'Material escolar'), ('outros', 'Outros')], max_length=30)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('unidade', models.CharField(blank=True, default='un', max_length=30)),
                ('data_validade', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('doacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_estoque', to='cadastros.doacao')),
            ],
            options={
                'ordering': ['data_validade', 'produto', 'id'],
                'constraints': [models.UniqueConstraint(fields=('produto', 'unidade', 'data_validade'), name='unique_lote_estoque_produto_unidade_validade')],
            },
        ),
    ]
